package com.example.data.export

import android.content.Context
import android.content.Intent
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import android.net.Uri
import androidx.core.content.FileProvider
import com.example.data.model.ExportFormat
import com.example.data.model.LeadEntity
import com.example.data.model.ScrapingFilterConfig
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

class ReportExporter(private val context: Context) {

    private val dateFormatter = SimpleDateFormat("yyyy-MM-dd_HHmmss", Locale.getDefault())
    private val displayDateFormatter = SimpleDateFormat("MMM dd, yyyy HH:mm", Locale.getDefault())

    suspend fun generateExportFile(
        leads: List<LeadEntity>,
        format: ExportFormat,
        filterConfig: ScrapingFilterConfig,
        entityType: String,
        targetLocation: String
    ): File = withContext(Dispatchers.IO) {
        val exportDir = File(context.cacheDir, "exports").apply {
            if (!exists()) mkdirs()
        }
        val timestampStr = dateFormatter.format(Date())
        val cleanType = entityType.lowercase(Locale.ROOT)
        val fileName = "leadscout_${cleanType}_${timestampStr}.${format.extension}"
        val file = File(exportDir, fileName)

        when (format) {
            ExportFormat.CSV -> writeCsvFile(file, leads, filterConfig)
            ExportFormat.EXCEL -> writeExcelFile(file, leads, filterConfig, entityType, targetLocation)
            ExportFormat.PDF -> writePdfFile(file, leads, entityType, targetLocation)
        }

        return@withContext file
    }

    fun createShareIntent(file: File, format: ExportFormat): Intent {
        val uri: Uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.fileprovider",
            file
        )

        val intent = Intent(Intent.ACTION_SEND).apply {
            type = format.mimeType
            putExtra(Intent.EXTRA_STREAM, uri)
            putExtra(Intent.EXTRA_SUBJECT, "LeadScout AI Extracted Leads Report")
            putExtra(
                Intent.EXTRA_TEXT,
                "Attached is the leads extraction report generated by LeadScout AI (${file.name}). Contains verified contact details, addresses, and quality ratings."
            )
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }

        return Intent.createChooser(intent, "Share Leads Report via")
    }

    private fun writeCsvFile(file: File, leads: List<LeadEntity>, filter: ScrapingFilterConfig) {
        val writer = file.bufferedWriter()
        writer.use { out ->
            val headers = mutableListOf<String>()
            if (filter.extractName) headers.add("Organization / Name")
            headers.add("Category")
            if (filter.extractLocation) headers.add("City")
            if (filter.extractLocation) headers.add("State")
            if (filter.extractLocation) headers.add("ZIP Code")
            if (filter.extractAddress) headers.add("Full Address")
            if (filter.extractWebsite) headers.add("Website")
            if (filter.extractEmail) headers.add("Email Address")
            if (filter.extractPhone) headers.add("Phone Number")
            if (filter.extractExecutive) headers.add("Key Executive / Contact")
            if (filter.extractLicenseRating) headers.add("License / Registry ID")
            if (filter.extractLicenseRating) headers.add("Rating / Accreditation")
            headers.add("Quality Score")
            headers.add("Extracted Date")

            out.write(headers.joinToString(",") { escapeCsv(it) })
            out.newLine()

            for (lead in leads) {
                val row = mutableListOf<String>()
                if (filter.extractName) row.add(lead.name)
                row.add(lead.category)
                if (filter.extractLocation) row.add(lead.city)
                if (filter.extractLocation) row.add(lead.state)
                if (filter.extractLocation) row.add(lead.zipCode)
                if (filter.extractAddress) row.add(lead.address)
                if (filter.extractWebsite) row.add(lead.website)
                if (filter.extractEmail) row.add(lead.email)
                if (filter.extractPhone) row.add(lead.phone)
                if (filter.extractExecutive) row.add(lead.contactPerson)
                if (filter.extractLicenseRating) row.add(lead.licenseOrRegistrationNo)
                if (filter.extractLicenseRating) row.add(lead.ratingOrAccreditation)
                row.add("${lead.leadQualityScore}/100")
                row.add(displayDateFormatter.format(Date(lead.timestamp)))

                out.write(row.joinToString(",") { escapeCsv(it) })
                out.newLine()
            }
        }
    }

    private fun writeExcelFile(
        file: File,
        leads: List<LeadEntity>,
        filter: ScrapingFilterConfig,
        entityType: String,
        targetLocation: String
    ) {
        val writer = file.bufferedWriter(Charsets.UTF_8)
        writer.use { out ->
            // Excel XML format for maximum compatibility and formatted headers
            out.write("<?xml version=\"1.0\"?>\n")
            out.write("<?mso-application progid=\"Excel.Sheet\"?>\n")
            out.write("<Workbook xmlns=\"urn:schemas-microsoft-com:office:spreadsheet\"\n")
            out.write(" xmlns:o=\"urn:schemas-microsoft-com:office:office\"\n")
            out.write(" xmlns:x=\"urn:schemas-microsoft-com:office:excel\"\n")
            out.write(" xmlns:ss=\"urn:schemas-microsoft-com:office:spreadsheet\"\n")
            out.write(" xmlns:html=\"http://www.w3.org/TR/REC-html40\">\n")

            // Styles
            out.write(" <Styles>\n")
            out.write("  <Style ss:ID=\"HeaderStyle\">\n")
            out.write("   <Font ss:Bold=\"1\" ss:Color=\"#FFFFFF\" ss:Size=\"11\"/>\n")
            out.write("   <Interior ss:Color=\"#1E3A8A\" ss:Pattern=\"Solid\"/>\n")
            out.write("   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Center\"/>\n")
            out.write("  </Style>\n")
            out.write("  <Style ss:ID=\"MetaStyle\">\n")
            out.write("   <Font ss:Bold=\"1\" ss:Color=\"#1E40AF\" ss:Size=\"12\"/>\n")
            out.write("  </Style>\n")
            out.write("  <Style ss:ID=\"ScoreStyle\">\n")
            out.write("   <Font ss:Bold=\"1\" ss:Color=\"#059669\"/>\n")
            out.write("   <Alignment ss:Horizontal=\"Center\"/>\n")
            out.write("  </Style>\n")
            out.write("  <Style ss:ID=\"HyperlinkStyle\">\n")
            out.write("   <Font ss:Color=\"#0284C7\" ss:Underline=\"Single\"/>\n")
            out.write("   <Alignment ss:Vertical=\"Center\"/>\n")
            out.write("  </Style>\n")
            out.write(" </Styles>\n")

            out.write(" <Worksheet ss:Name=\"Extracted Leads\">\n")
            out.write("  <Table>\n")

            // Title Row
            out.write("   <Row>\n")
            out.write("    <Cell ss:StyleID=\"MetaStyle\"><Data ss:Type=\"String\">LeadScout AI Intelligence Report - $entityType ($targetLocation)</Data></Cell>\n")
            out.write("   </Row>\n")
            out.write("   <Row>\n")
            out.write("    <Cell><Data ss:Type=\"String\">Total Records: ${leads.size} | Generated on ${displayDateFormatter.format(Date())}</Data></Cell>\n")
            out.write("   </Row>\n")
            out.write("   <Row></Row>\n")

            // Header Row
            val headers = mutableListOf<String>()
            if (filter.extractName) headers.add("Company / Institution")
            headers.add("Category / Line")
            if (filter.extractLocation) headers.add("City")
            if (filter.extractLocation) headers.add("State")
            if (filter.extractLocation) headers.add("ZIP")
            if (filter.extractAddress) headers.add("Full Address")
            if (filter.extractWebsite) headers.add("Website Link")
            if (filter.extractEmail) headers.add("Email ID")
            if (filter.extractPhone) headers.add("Phone Contact")
            if (filter.extractExecutive) headers.add("Contact Person / Exec")
            if (filter.extractLicenseRating) headers.add("Registry / NAIC License")
            if (filter.extractLicenseRating) headers.add("Rating / Accreditation")
            headers.add("Lead Score")

            out.write("   <Row>\n")
            for (h in headers) {
                out.write("    <Cell ss:StyleID=\"HeaderStyle\"><Data ss:Type=\"String\">$h</Data></Cell>\n")
            }
            out.write("   </Row>\n")

            // Data Rows
            for (lead in leads) {
                out.write("   <Row>\n")
                if (filter.extractName) out.write("    <Cell><Data ss:Type=\"String\">${escapeXml(lead.name)}</Data></Cell>\n")
                out.write("    <Cell><Data ss:Type=\"String\">${escapeXml(lead.category)}</Data></Cell>\n")
                if (filter.extractLocation) out.write("    <Cell><Data ss:Type=\"String\">${escapeXml(lead.city)}</Data></Cell>\n")
                if (filter.extractLocation) out.write("    <Cell><Data ss:Type=\"String\">${escapeXml(lead.state)}</Data></Cell>\n")
                if (filter.extractLocation) out.write("    <Cell><Data ss:Type=\"String\">${escapeXml(lead.zipCode)}</Data></Cell>\n")
                if (filter.extractAddress) out.write("    <Cell><Data ss:Type=\"String\">${escapeXml(lead.address)}</Data></Cell>\n")
                if (filter.extractWebsite) {
                    val rawUrl = lead.website.trim()
                    val validHref = if (rawUrl.startsWith("http://", ignoreCase = true) || rawUrl.startsWith("https://", ignoreCase = true)) {
                        rawUrl
                    } else if (rawUrl.isNotEmpty() && !rawUrl.contains(" ") && rawUrl != "[Filter Excluded]") {
                        "https://$rawUrl"
                    } else null

                    if (validHref != null) {
                        out.write("    <Cell ss:StyleID=\"HyperlinkStyle\" ss:HRef=\"${escapeXml(validHref)}\"><Data ss:Type=\"String\">${escapeXml(lead.website)}</Data></Cell>\n")
                    } else {
                        out.write("    <Cell><Data ss:Type=\"String\">${escapeXml(lead.website)}</Data></Cell>\n")
                    }
                }
                if (filter.extractEmail) {
                    val rawEmail = lead.email.trim()
                    if (rawEmail.contains("@") && !rawEmail.contains(" ") && rawEmail != "[Filter Excluded]") {
                        out.write("    <Cell ss:StyleID=\"HyperlinkStyle\" ss:HRef=\"mailto:${escapeXml(rawEmail)}\"><Data ss:Type=\"String\">${escapeXml(lead.email)}</Data></Cell>\n")
                    } else {
                        out.write("    <Cell><Data ss:Type=\"String\">${escapeXml(lead.email)}</Data></Cell>\n")
                    }
                }
                if (filter.extractPhone) out.write("    <Cell><Data ss:Type=\"String\">${escapeXml(lead.phone)}</Data></Cell>\n")
                if (filter.extractExecutive) out.write("    <Cell><Data ss:Type=\"String\">${escapeXml(lead.contactPerson)}</Data></Cell>\n")
                if (filter.extractLicenseRating) out.write("    <Cell><Data ss:Type=\"String\">${escapeXml(lead.licenseOrRegistrationNo)}</Data></Cell>\n")
                if (filter.extractLicenseRating) out.write("    <Cell><Data ss:Type=\"String\">${escapeXml(lead.ratingOrAccreditation)}</Data></Cell>\n")
                out.write("    <Cell ss:StyleID=\"ScoreStyle\"><Data ss:Type=\"Number\">${lead.leadQualityScore}</Data></Cell>\n")
                out.write("   </Row>\n")
            }

            out.write("  </Table>\n")
            out.write(" </Worksheet>\n")
            out.write("</Workbook>\n")
        }
    }

    private fun writePdfFile(
        file: File,
        leads: List<LeadEntity>,
        entityType: String,
        targetLocation: String
    ) {
        val pdfDocument = PdfDocument()
        val pageWidth = 595 // A4 standard width in points
        val pageHeight = 842 // A4 standard height in points
        var pageNumber = 1

        val pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create()
        var page = pdfDocument.startPage(pageInfo)
        var canvas = page.canvas

        val paintTitle = Paint().apply {
            color = Color.rgb(30, 58, 138)
            textSize = 16f
            isFakeBoldText = true
            isAntiAlias = true
        }

        val paintSubtitle = Paint().apply {
            color = Color.rgb(71, 85, 105)
            textSize = 9f
            isAntiAlias = true
        }

        val paintHeaderBg = Paint().apply {
            color = Color.rgb(239, 246, 255)
        }

        val paintCardBg = Paint().apply {
            color = Color.rgb(248, 250, 252)
        }

        val paintCardBorder = Paint().apply {
            color = Color.rgb(226, 232, 240)
            style = Paint.Style.STROKE
            strokeWidth = 1f
        }

        val paintBoldText = Paint().apply {
            color = Color.rgb(15, 23, 42)
            textSize = 10f
            isFakeBoldText = true
            isAntiAlias = true
        }

        val paintBodyText = Paint().apply {
            color = Color.rgb(51, 65, 85)
            textSize = 8.5f
            isAntiAlias = true
        }

        val paintScorePill = Paint().apply {
            color = Color.rgb(5, 150, 105)
            textSize = 8.5f
            isFakeBoldText = true
            isAntiAlias = true
        }

        // Draw Header
        canvas.drawRect(0f, 0f, pageWidth.toFloat(), 70f, paintHeaderBg)
        canvas.drawText("LeadScout AI - Data Extraction & Research Report", 24f, 32f, paintTitle)
        canvas.drawText(
            "Category: $entityType  |  Location: $targetLocation  |  Total Extracted: ${leads.size}  |  Date: ${displayDateFormatter.format(Date())}",
            24f,
            50f,
            paintSubtitle
        )

        var yOffset = 90f
        val cardHeight = 84f
        val margin = 24f
        val cardWidth = pageWidth - (margin * 2)

        for ((index, lead) in leads.withIndex()) {
            if (yOffset + cardHeight > pageHeight - 40f) {
                pdfDocument.finishPage(page)
                pageNumber++
                val nextInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create()
                page = pdfDocument.startPage(nextInfo)
                canvas = page.canvas

                // Draw header on subsequent pages
                canvas.drawRect(0f, 0f, pageWidth.toFloat(), 45f, paintHeaderBg)
                canvas.drawText("LeadScout AI Report (Page $pageNumber) - $entityType ($targetLocation)", 24f, 28f, paintTitle)
                yOffset = 60f
            }

            // Draw Card background
            canvas.drawRect(margin, yOffset, margin + cardWidth, yOffset + cardHeight, paintCardBg)
            canvas.drawRect(margin, yOffset, margin + cardWidth, yOffset + cardHeight, paintCardBorder)

            // Left Lead Info
            val leadNum = "${index + 1}. "
            canvas.drawText(
                leadNum + lead.name.take(45),
                margin + 12f,
                yOffset + 18f,
                paintBoldText
            )
            canvas.drawText(
                "Category: ${lead.category}  |  License: ${lead.licenseOrRegistrationNo}",
                margin + 12f,
                yOffset + 32f,
                paintBodyText
            )
            canvas.drawText(
                "Address: ${lead.address.ifEmpty { "${lead.city}, ${lead.state} ${lead.zipCode}" }}",
                margin + 12f,
                yOffset + 46f,
                paintBodyText
            )
            canvas.drawText(
                "Email: ${lead.email}   |   Phone: ${lead.phone}",
                margin + 12f,
                yOffset + 60f,
                paintBodyText
            )
            canvas.drawText(
                "Web: ${lead.website}   |   Contact: ${lead.contactPerson}",
                margin + 12f,
                yOffset + 74f,
                paintBodyText
            )

            // Right Score Badge
            canvas.drawText(
                "Score: ${lead.leadQualityScore}/100",
                margin + cardWidth - 85f,
                yOffset + 18f,
                paintScorePill
            )
            canvas.drawText(
                lead.ratingOrAccreditation.take(20),
                margin + cardWidth - 105f,
                yOffset + 34f,
                paintSubtitle
            )

            yOffset += cardHeight + 8f
        }

        // Draw Footer
        canvas.drawText(
            "Generated securely with LeadScout AI Platform - Page $pageNumber",
            24f,
            pageHeight - 15f,
            paintSubtitle
        )

        pdfDocument.finishPage(page)

        FileOutputStream(file).use { out ->
            pdfDocument.writeTo(out)
        }
        pdfDocument.close()
    }

    private fun escapeCsv(value: String): String {
        var str = value.replace("\"", "\"\"")
        if (str.contains(",") || str.contains("\n") || str.contains("\r") || str.contains("\"")) {
            str = "\"$str\""
        }
        return str
    }

    private fun escapeXml(value: String): String {
        return value.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")
            .replace("'", "&apos;")
    }
}
